# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$ZDOTDIR/oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git gh kube-ps1 z fzf zsh-autosuggestions aws)
source $ZSH/oh-my-zsh.sh

# User configuration

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

source $ZDOTDIR/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f $ZDOTDIR/p10k.zsh ]] || source $ZDOTDIR/p10k.zsh

# initialization of config files
SHELL_DIR="${0:A:h}"

load () {
  if [ -f "$1" ]; then
      source "$1"
  else
      print "$1 not found."
  fi
}

autoload -Uz compinit && compinit
autoload -U +X bashcompinit && bashcompinit

load "$SHELL_DIR/aliases.sh"
load "$ZDOTDIR/setup"

setopt nocorrectall
setopt correct

eval "$(atuin init zsh --disable-up-arrow)"
if type gdircolors >/dev/null; then
  eval "$(gdircolors $HOME/.config/zsh/dircolors.everforest)"
fi
if type dircolors >/dev/null; then
  eval "$(dircolors $HOME/.config/zsh/dircolors.everforest)"
fi
source <(cilium completion zsh)

if type hubble >/dev/null; then
  source <(hubble completion zsh)
fi

eval "$(/opt/homebrew/bin/brew shellenv)"

fpath+=(/opt/homebrew/share/zsh/site-functions)
