[colors.bright]
black = "#475258"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.normal]
black = "#414b50"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.primary]
background = "#2D353B"
foreground = "#d3c6aa"

[font]
size = 11

[font.normal]
#family = "JetBrains Mono Nerd Font"
#style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.98

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 8
y = 5
